swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /people:
    get:
      operationId: "people.read"
      tags:
        - "People"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: "array"
            items:
              properties:
                fname:
                  type: "string"
                lname:
                  type: "string"
                timestamp:
                  type: "string"
    post:
      operationId: people.create
      tags:
        - "People"
      summary: Create a person and add it to the people list
      description: Create a new person in the people list
      parameters:
        - name: person
          in: body
          description: person to create
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
                description: first name of person
              lname:
                type: string
                description: last name of person
      responses:
        201:
          description: success creation
  /people/{lname}:
    get:
      operationId: people.read_one
      tags:
        - "People"
      summary: Read one person from the people list
      description: read on person from the people list
      parameters:
        - name: lname
          in: path
          description: Last name of the person to get
          type: string
          required: True
      responses:
        200:
          description: Success read person
          schema:
            properties:
              fname:
                 type: string
              lname:
                 type: string
              timestamp:
                 type: string